// components/Kwitizina.tsx
export default function Ceremonies(){
    return (
    <div className="flex flex-col w-full unlimited">
	<div className="w-full">
		<div className="bg-green-600 rounded p-4 cursor-pointer">
			<h3 className="text-white">New Ceremony</h3>
		</div>
	</div>
	<div className="w-full">
		<table className="w-full justify-between mt-0">
			<thead className="w-full">
				<tr className="justify-between">
					<th className="p-4 w-1/6">Year</th>
					<th className="p-4 w-1/6">Special Guests</th>
					<th className="p-4 w-1/6">Gorillas named</th>
					<th className="p-4 w-1/6">Namers</th>
					<th className="p-4 w-1/6">Full Date</th>
					<th className="p-4 w-1/6">Location</th>
				</tr>
			</thead>
			<tbody className="w-full">
				<tr className="mt-3 justify-between bg-white border-b hover:bg-green-100 transition-all cursor-pointer ">
					<td className="text-center p-4 w-1/6">2020</td>
					<td className="text-center p-4 w-1/6">18</td>
					<td className="text-center p-4 w-1/6 text-sm">27</td>
					<td className="text-center w-1/6 text-sm">27</td>
					<td className="text-center p-4 w-1/6">22<sup>nd</sup> September</td>
					<td className=" text-center p-4 w-1/6">Kinigi</td>
				</tr>
				<tr className="mt-3 justify-between bg-white border-b hover:bg-green-100 transition-all cursor-pointer ">
					<td className="text-center p-4 w-1/6">2019</td>
					<td className="text-center p-4 w-1/6">18</td>
					<td className="text-center p-4 w-1/6 text-sm">27</td>
					<td className="text-center w-1/6 text-sm">27</td>
					<td className="text-center p-4 w-1/6">22<sup>nd</sup> September</td>
					<td className=" text-center p-4 w-1/6">Kinigi</td>
				</tr>
				<tr className="mt-3 justify-between bg-white border-b hover:bg-green-100 transition-all cursor-pointer ">
					<td className="text-center p-4 w-1/6">2018</td>
					<td className="text-center p-4 w-1/6">18</td>
					<td className="text-center p-4 w-1/6 text-sm">27</td>
					<td className="text-center w-1/6 text-sm">27</td>
					<td className="text-center p-4 w-1/6">22<sup>nd</sup> September</td>
					<td className=" text-center p-4 w-1/6">Kinigi</td>
				</tr>
				<tr className="mt-3 justify-between bg-white border-b hover:bg-green-100 transition-all cursor-pointer ">
					<td className="text-center p-4 w-1/6">2017</td>
					<td className="text-center p-4 w-1/6">18</td>
					<td className="text-center p-4 w-1/6 text-sm">27</td>
					<td className="text-center w-1/6 text-sm">27</td>
					<td className="text-center p-4 w-1/6">22<sup>nd</sup> September</td>
					<td className=" text-center p-4 w-1/6">Kinigi</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
)
}

// src/routes/admin/kwitizina.svelte
<div class="w-full flex flex-col">
        <ul class="w-full flex items-center mx-auto md:mb-4">
            <li class="w-1/2 text-center font-semibold cursor-pointer text-green-600">Ceremonies</li>
            <li class="w-1/2 text-center font-semibold cursor-pointer">Namers</li>
        </ul>
        <div
        class="bg-white rounded px-4 pt-3 pb-1 md:px-8 md:py-3 mr-3 md:flex md:w-11/12 longer"
      >
      <table class="w-full">
          <thead>
              <tr>
                  <td></td>
                  <td class="font-semibold text-gray-700">Namer</td>
                  <td class="font-semibold text-gray-700">Contact</td>
                  <td class="font-semibold text-gray-700">Gorilla named</td>
                  <td class="font-semibold text-gray-700">More</td>
              </tr>
          </thead>
          <tbody>
              <tr class="border-b-4">
                  <td class="py-4">1</td>
                  <td class="py-4">Didier Munezero</td>
                  <td class="py-4">0782915222</td>
                  <td class="py-4">Umucyo</td>
                  <td class="py-4">Former Pr Uganda</td>
              </tr>
              <tr class="border-b-4">
                <td class="py-4">1</td>
                <td class="py-4">Didier Munezero</td>
                <td class="py-4">0782915222</td>
                <td class="py-4">Umucyo</td>
                <td class="py-4">Former Pr Uganda</td>
            </tr>
            <tr class="border-b-4">
                <td class="py-4">1</td>
                <td class="py-4">Didier Munezero</td>
                <td class="py-4">0782915222</td>
                <td class="py-4">Umucyo</td>
                <td class="py-4">Former Pr Uganda</td>
            </tr>
            <tr class="border-b-4">
                <td class="py-4">1</td>
                <td class="py-4">Didier Munezero</td>
                <td class="py-4">0782915222</td>
                <td class="py-4">Umucyo</td>
                <td class="py-4">Former Pr Uganda</td>
            </tr>
            <tr class="border-b-4">
                <td class="py-4">1</td>
                <td class="py-4">Didier Munezero</td>
                <td class="py-4">0782915222</td>
                <td class="py-4">Umucyo</td>
                <td class="py-4">Former Pr Uganda</td>
            </tr>
          </tbody>
      </table>
    </div>
</div>
