// src/components/Settings.svelte
<script lang="ts">
  let photoUrl: string =
    "https://avatars.githubusercontent.com/u/52195?s=460&u=08bcafa24337a298e1b874279fde515e2fb8f81d&v=4"
</script>
<svelte:head>
	<title>Settings</title>
</svelte:head>
<div>
  <div class="px:2 m-2 md:px-5 md:m-5 md:mt-1">
    <h1 class="text-xl font-semibold text-center md:text-left">
      Profile Settings
    </h1>
  </div>
  <div
    class="bg-white rounded px-4 pt-3 pb-1 md:px-8 md:py-3 mr-3 md:flex w-5/6 longer"
  >
    <div class="mr-10 mt-2">
      <ul>
        <li
          class="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1 text-motherGreen"
        >
          Profile
        </li>
        <li
          class="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1"
        >
          Notifications
        </li>
        <li
          class="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1"
        >
          Password
        </li>
        <li
          class="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1"
        >
          Messages
        </li>
      </ul>
    </div>
    <div class="rounded shadow w-4/5 h-full md:ml-4 mt-2 flex flex-col">
      <h1 class="text-center font-semibold text-xl">Account</h1>
      <div class="mt-6 mx-auto items-center">
        <img class="img rounded-full" src={photoUrl} alt="" />
        <div class="flex mt-1">
          <button
            class="text-green-500 p-1 px-2 mx-1 focus:outline-none rounded shadow"
            >Upload</button
          >
          <button
            class="border border-red-500 text-red-500 p-1 px-2 mx-1 shadow rounded focus:outline-none "
            >Remove</button
          >
        </div>
      </div>
      <div class="mb-10">
      <div class="mt-1 mx-auto flex flex-col w-11/12 md:w-9/12">
        <label for="name" class="font-semibold ml-1">Add Bio</label>
        <textarea class="autoexpand tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full border-2 rounded focus:outline-none border-green"
        id="message" type="text" placeholder="Message..."></textarea>
      </div>
      <div class="mt-1 mx-auto md:flex w-11/12 md:w-9/12">
        <div class="flex flex-col md:mx-0 md:w-6/12">
          <label for="name" class="font-semibold ml-1">First Name</label>
          <input type="text" name="fname" class="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green" />
        </div>
        <div class="flex flex-col md:ml-2 md:w-6/12">
          <label for="name" class="font-semibold ml-1">Last Name</label>
          <input type="text" name="lname" class="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green" />
        </div>
      </div>
      <div class="mt-1 mx-auto md:flex w-11/12 md:w-9/12">
        <div class="flex flex-col md:mx-0 md:w-6/12">
          <label for="name" class="font-semibold ml-1">Email</label>
          <input type="email" name="email" class="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green" />
        </div>
        <div class="flex flex-col md:ml-2 md:w-6/12">
          <label for="name" class="font-semibold ml-1">Phone Number</label>
          <input type="text" name="phone" class="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green" />
        </div>
      </div>
      <div class="mt-1 mx-auto md:flex w-11/12 md:w-9/12">
        <div class="flex flex-col md:mx-0 md:w-6/12">
          <label for="name" class="font-semibold ml-1">Province</label>
          <input type="text" name="province" class="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green" />
        </div>
        <div class="flex flex-col md:ml-2 md:w-6/12">
          <label for="name" class="font-semibold ml-1">District</label>
          <input type="text" name="district" class="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green" />
        </div>
      </div>
      <div class="mt-1 mx-auto flex w-11/12 md:w-9/12 items-center mt-2">
        <div class="flex flex-col w-full">
          <button type="submit" class="bg-green py-1 font-semibold rounded focus:outline-none">Save Changes</button>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

<style>
  .bg-green{
    background-color: #00917C;
    color: white;
  }
  .text-red-500 {
    color: #E74C3C;
    border: 1.5px solid  #E74C3C;
  }
  .text-s-xl {
    font-size: 17px;
  }
  .border-green:focus{
    border-color: #00917C;
  }
  .text-green-500{
    color: #00917C;
    border: 1.5px solid  #00917C;
  }
  .longer {
    height: fit-content;
  }
  .img{
    width: 120px;
    height: 120px;
  }
  @media only screen and (max-height: 340px) {
    .longer {
      height: fit-content;
      width: fit-content;
    }
  }
  @media only screen and (max-width: 700px) {
    .longer {
      height: fit-content;
      width: fit-content;
    }
  }
  div *::-webkit-scrollbar {
    width: 4px;
  }
  div *::-webkit-scrollbar-track {
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }

  div::-webkit-scrollbar-thumb {
    background-color: darkgrey;
    outline: 1px solid slategrey;
  }
</style>

// components/Settings.tsx
export default function Settings(){
    const user = {
        photo:'https://avatars.githubusercontent.com/u/51176044?v=4'
    }
    return(
        <div>
	<div
		className="bg-white w-full rounded px-4 pt-3 pb-1 md:px-8 md:py-3 md:mr-3 md:flex md:w-5/6 longer"
	>
		<div className="mr-10 mt-2">
			<ul>
				<li
					className="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1 text-motherGreen"
				>
					Profile
				</li>
				<li className="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1">
					Notifications
				</li>
				<li className="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1">Password</li>
				<li className="text-s-xl font-semibold hover:text-motherGreen cursor-pointer p-1">Messages</li>
			</ul>
		</div>
		<form
			className="rounded shadow w-full md:w-4/5 h-full md:ml-4 mt-2 flex flex-col"
		>
			<h1 className="text-center font-semibold text-xl md:-ml-20">Account</h1>
			<div className="mt-6 mx-auto items-center">
				<input className="hidden"
					type="file"
					accept=".jpg, .jpeg, .png"
				/>
					<img src={user.photo} alt="..." className="img h-20 w-20 rounded-full" />
				<div className="flex mt-1">
					<span
						className="w-20 text-center border border-green-500 text-green-500 p-1 px-2 mx-1 focus:outline-none rounded shadow cursor-pointer">Upload</span
					>
					<span
						className="w-20 text-center border border-red-500 text-red-500 p-1 px-2 mx-1 shadow rounded focus:outline-none cursor-pointer"
						>Remove</span
					>
				</div>
			</div>
			<div className="mb-10">
				<div className="mt-1 mx-auto flex flex-col w-11/12 md:w-9/12">
					<label className="font-semibold ml-1">Add Bio</label>
					<textarea
						className="autoexpand tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full border-2 rounded focus:outline-none border-green"
						id="message"
						placeholder="Message..."
					/>
				</div>
				<div className="mt-1 mx-auto md:flex w-11/12 md:w-9/12">
					<div className="flex flex-col md:mx-0 md:w-6/12">
						<label className="font-semibold ml-1">First Name</label>
						<input
							type="text"
							name="fname"
							className="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green"
						/>
					</div>
					<div className="flex flex-col md:ml-2 md:w-6/12">
						<label className="font-semibold ml-1">Last Name</label>
						<input
							type="text"
							name="lname"
							className="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green"
						/>
					</div>
				</div>
				<div className="mt-1 mx-auto md:flex w-11/12 md:w-9/12">
					<div className="flex flex-col md:mx-0 md:w-6/12">
						<label className="font-semibold ml-1">Email</label>
						<input
							type="email"
							name="email"
							className="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green"
						/>
					</div>
					<div className="flex flex-col md:ml-2 md:w-6/12">
						<label className="font-semibold ml-1">Phone Number</label>
						<input
							type="text"
							name="phone"
							className="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green"
						/>
					</div>
				</div>
				<div className="mt-1 mx-auto md:flex w-11/12 md:w-9/12">
					<div className="flex flex-col md:mx-0 md:w-6/12">
						<label className="font-semibold ml-1">Province</label>
						<input
							type="text"
							name="province"
							className="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green"
						/>
					</div>
					<div className="flex flex-col md:ml-2 md:w-6/12">
						<label className="font-semibold ml-1">District</label>
						<input
							type="text"
							name="district"
							className="w-full px-3 py-1 text-sm  border-2 rounded focus:outline-none border-green"
						/>
					</div>
				</div>
				<div className="mx-auto flex w-11/12 md:w-9/12 items-center mt-2">
					<div className="flex flex-col w-full">
						<button type="submit" className="bg-green py-1 font-semibold rounded focus:outline-none"
							>Save Changes</button
						>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
    )
}
