// src/components/Sidebar.svelte
<script lang="ts">
  import type List from "../types/sidebar_items"
  export let list: List[]
</script>

<div
  class="flex flex-col w-56 bg-white  overflow-hidden h-screen justify-between"
>
  <div class="">
    <div class="flex items-center justify-center h-20 shadow-md">
      <a href="/">
        <h1 class="text-3xl uppercase text-red-500">NPMG</h1>
      </a>
    </div>
    <ul class="flex flex-col py-4">
      {#each list as item}
        <li>
          <a
            href={item.url}
            class="flex flex-row items-center h-12 transform  text-gray-800 hover:text-motherGreen"
          >
            <span
              class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-800"
              ><i class="bx bx-home" /></span
            >
            <span class="text-sm font-medium">{item.name}</span>
          </a>
        </li>
      {/each}
    </ul>
  </div>
  <div>
    <h1
      class="text-red-500 font-semibold bg-logout px-4 py-2 text-center bottom-0 cursor-pointer"
    >
      Logout
    </h1>
  </div>
</div>

// components/SideBar.tsx
import { useRouter } from "next/router";
import Link from 'next/link'
export default function Sidebar({items}){
    const router = useRouter();
    return(
        <div className="flex bg-white h-screen  shadow-md flex-col justify-between">
			<div>
	       <h2 className="text-3xl uppercase font-sans font-extrabold px-4 mb-10 mt-10">NPMG</h2>
	        <div className="flex flex-col py-4">
            {items.map((item) => (
            item.url == router.pathname ?(
                <div key={item.url}>
					<Link href={item.url}>
					<a
						className="px-4 flex flex-row items-center h-10 transform  bg-gray-200 border-r-4 border-green-600 font-semibold"
					>
						{item.name}
					</a>
					</Link>
				</div>
            ):(
                <div key={item.url}>
					<Link href={item.url}>
					<a
						className="px-4 flex flex-row items-center h-10 transform  text-gray-800 hover:text-motherGreen"
					>
						{item.name}
					</a>
					</Link>
				</div>
            )
            ))}
			</div>
		</div>
		<div className="mb-3">
		<Link href="/signin">
			<a
				className="text-red-500 font-semibold px-4 py-4 text-center bottom-0 cursor-pointer font-sourceSans"
				>Logout</a
			>
		</Link>
		</div>
	
</div>
    )
}
